export const START_YEAR = new Date().getFullYear()
export const NUM_OF_YEARS = 1
export const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
export const MONTHS_PER_YEAR = 12
export const NUM_OF_MONTHS = NUM_OF_YEARS * MONTHS_PER_YEAR
export const MAX_TRACK_START_GAP = 4
export const MAX_ELEMENT_GAP = 8
export const MAX_MONTH_SPAN = 8
export const MIN_MONTH_SPAN = 2
export const NUM_OF_TRACKS = 20
export const MAX_NUM_OF_SUBTRACKS = 5

export const BASE_URL = "http://localhost:8081"
export const GET_ALL_APARTMENTS_URL = "/getAllApartments/"
export const CREATE_URL = "/createApartment/"
export const DELETE_URL = "/deleteApartment/"
export const CREATE_TENANT = "/createTenant/"
export const DELETE_TENANT = "/deleteTenant/"
export const DELETE_TENANT_ALL = "/deleteAllTenants/"
export const DELETE_TENANT_GROUP = "/deleteTenantGroup/"
export const CREATE_BUILDING = "/createBuilding/"
export const DELETE_BUILDING = "/deleteBuilding/"
export const CREATE_LANDLORD = "/createLandlord/"
export const DELETE_LANDLORD = "/deleteLandlord/"
export const GET_APART_NUM = "/getApartmentByNumber/"
export const GET_APART_BUILDING = "/getApartmentByBuilding/"
export const GET_APART_LANDLORD = "/getApartmentByLandlord/"
export const GET_ALL_BUILDINGS = "/getAllBuildings/"
export const GET_ALL_TENANTS = "/getAllTenants/"
export const GET_ALL_LANDLORDS = "/getAllLandlords/"
